### ISSUE TITLE
Save .navbar-toggler-icon State in LocalStorage

### ISSUE THREAD

**Issue by s0kil** [chartio/dataschool#98]
When closing navbar, it reopens when loading next lesson, becomes annoying.

**Comment by fronofro** [comment]
Thanks for flagging, we will take a look!

**Comment by s0kil** [comment]
It has to do with [footer.html](https://github.com/chartio/dataschool/blob/master/dataschool/_includes/footer.html#L15-L21)

I would send PR, but I could not get `bundler` installed to test.
